name: Update YouTube Subscribers

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: # 手动触发支持

jobs:
  update-subscribers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch YouTube subscribers
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: |
        # 创建 fetch-subscribers.js 文件
        echo "const fs = require('fs');" > fetch-subscribers.js
        echo "const fetch = require('node-fetch');" >> fetch-subscribers.js
        echo "const apiKey = process.env.YOUTUBE_API_KEY;" >> fetch-subscribers.js
        echo "const channelId = process.env.CHANNEL_ID;" >> fetch-subscribers.js
        echo "const url = `https://www.googleapis.com/youtube/v3/channels?part=statistics&id=${channelId}&key=${apiKey}`;" >> fetch-subscribers.js
        echo "fetch(url)" >> fetch-subscribers.js
        echo "  .then(response => response.json())" >> fetch-subscribers.js
        echo "  .then(data => {" >> fetch-subscribers.js
        echo "    const stats = data.items[0].statistics;" >> fetch-subscribers.js
        echo "    const result = {" >> fetch-subscribers.js
        echo "      subscriberCount: stats.subscriberCount," >> fetch-subscribers.js
        echo "      viewCount: stats.viewCount," >> fetch-subscribers.js
        echo "      videoCount: stats.videoCount," >> fetch-subscribers.js
        echo "      lastUpdated: new Date().toISOString()" >> fetch-subscribers.js
        echo "    };" >> fetch-subscribers.js
        echo "    fs.writeFileSync('youtube-stats.json', JSON.stringify(result, null, 2));" >> fetch-subscribers.js
        echo "  })" >> fetch-subscribers.js
        echo "  .catch(error => console.error('Error fetching data:', error));" >> fetch-subscribers.js

        # 安装 Node.js 并运行脚本
        sudo apt-get update
        sudo apt-get install -y nodejs npm
        npm install node-fetch@2
        node fetch-subscribers.js

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add youtube-stats.json
        git commit -m "Update YouTube subscribers"
        git push
